[package]
name = "scammed"
version = "0.1.0"
edition = "2021"

[dependencies]
anathema = { git = "https://github.com/togglebyte/anathema/", branch = "dev" }
rand = "0.8.5"
syntect = "5.2.0"
crossterm = "0.27.0"